### ISSUE TITLE
allow select specific instance from configs 

### ISSUE THREAD

**Issue by ibrahimjelliti** [christian-calabrese/leapp-ssm-tunnels-plugin#12]
**Is your feature request related to a problem? Please describe.**
When I want to SSM to ec2  instance, I list all my bastion instances in the configs array. the plugin by default open run was ssm start-session overall array items. while I want to ssm to the specific target instances.

**Describe the solution you'd like**
In Leapp I should be able to see my list of targets for the selected role and start a session in shell on the item I clicked from that list.

**Comment by christian-calabrese** [comment]
Hello Ibrahim,
Thank you for submitting this issue. That's a great idea, but as of now, the interface exposed by the Leapp plugins system does not allow such thing as showing more items in the plugins list.

**Comment by ibrahimjelliti** [comment]
Hi Christian, I see that from the plugin blueprint, maybe as a workaround the configs json file should be with yaml extension to allow commenting out targets not willing to ssm in the config. bit manual but works as a Leapp plugin.

**Comment by christian-calabrese** [comment]
That's a great idea, still simple thing to implement! Thank you

**Comment by ibrahimjelliti** [comment]
great work @christian-calabrese, it works fine, I keep only the yaml file for readability and the possibility of adding comments.
would be great if the leap interface allow more interactivity with the interface via modal.
